services:
  bye:
    build: ./bye
    ports:
      - "8082:8082"
    networks:
      - all

  api:
    build: ./api_gateway
    ports:
      - "8081:8081"
    networks:
      - all

  myhtml:
    build: ./myhtml
    ports:
      - "8080:8080"
    networks:
      - all

networks:
  all:
    driver: bridge
